### ISSUE TITLE
Does this need to be compiled?

### ISSUE THREAD

**Issue by starsinmypockets** [mdb/seaweed-cli#1]
Maybe the readme should contain instrucitons?

**Comment by mdb** [comment]
@starsinmypockets Good call -- installation instructions are on my TODO list.

Here are some instructions to un-block you:

1. install go.
2. make sure you have your `$GOPATH` env var established. For example, mine is `~/dev/go`.
3. `git clone` the `seaweed-cli` repo to the proper destination in your `$GOPATH`. For example, mine is at: `~/dev/go/src/github.com/mdb/seaweed-cli`.
4. `cd` into your `seaweed-cli` repo.
5. `go get` to install dependencies.
6. `go install` to compile and install `seaweed-cli`.
7. Enter the `seaweed-cli` command for usage instructions.

In the meantime, I'll research the preferred way to make available the compiled binary for users to download such that steps 1 - 7 above aren't necessary.

**Comment by starsinmypockets** [comment]
:D

**Comment by mdb** [comment]
Note that there are also now binary releases, which can be downloaded and installed directly from Github as is outlined in [README instructions](https://github.com/mdb/seaweed-cli#installation).
